import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'
import '@/utils/scheduler'
import DarkModeToggle from '@/components/DarkModeToggle'
import NotificationsPanel from '@/components/NotificationsPanel'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from 'next-auth'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100`}
      >
        <header className='p-4 flex justify-between items-center'>
          <div className='flex space-x-4'>
            <DarkModeToggle />
          </div>
          {session && <NotificationsPanel />}
        </header>
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
